### ISSUE TITLE
Carriers installed by modules are not selectable

### ISSUE THREAD

**Issue by boxdrop** [PrestaShop/ebay#11]
Hi there,

may I ask why you are excluding carriers installed by modules (thus, having carrier.is_module = 1) in EbayFormShippingTab? 

Basically this behavior comes from just using the default parameter for Carrier::getCarriers ($modules_filters = Carrier::PS_CARRIERS_ONLY), so it would be rather easy to remove this limitation.

Thanks,
boxdrop

**Comment by thoma202** [comment]
Hi Boxdrop, 

This limitation is not a technical limitation but a functionnal. Indeed a lot of module shippings need more informations, than the one that will be send by ebay, and this creates fatal error in most of the case, so this is a protection of the module to prevent this errors. 

I hope this answers to your question. 

Thoma

**Comment by boxdrop** [comment]
Sorry I cannot understand the reason for doing this.
This decision actively blocks any external carrier modules that aims at optimizing the user experience for both admins and / or customers. There is no way to get around this for modules that do work fine with your data supply.
Given the fact that especially ebay is a huge market to be targeted by shops, my understanding would be to actually give people a chance to partiticpate instead of just locking them out. Same goes for developers of modules that are incompatible in their current implementation. I am pretty sure they will adjust their modules once they have unsatisfied shops complaining.

**Comment by thoma202** [comment]
Hi Boxdrop. 

This was a real problem. Indeed at the beginning we used to let all the shipping services of PrestaShop but this lead to a lot of support for which users thought it was from ebay, but came from just functional incompatibility between ebay and the shipping module. As we could not support all the requests we decided to simply change the process and forbid the user to user shipping carrier linked to a module. 

You can still change this behavior in your module, because certainly some shipping modules are compatible with ebay, but we will be abble to support you in case of order failing because of the shipping service you've choose if you choose a shipping service link to a module as this is not supported by the module. 

I hope you'll understand that we have to have limitations on the use of the module as it is a quite complex module. 

Thoma
